#! /bin/sh

bspc config border_width       1
bspc config window_gap         20
bspc config focused_border_color "#82b1ff"
bspc config presel_feedback_color "#aa99aa"
bspc config normal_border_color "#000000"

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config top_padding 20
bspc config bottom_padding 0
bspc config click_to_focus button1
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a feh state=floating border=off

pgrep -f '(lemonbuddy_wrapper.sh|^lemonb(uddy|ar))' | xargs kill -9 >/dev/null 2>&1

lemonbuddy top &

wait
