#! /bin/sh

## DEPENDENCIES dunno if this is accurate
# feh
# sutils
# 

cd ~/.config/bspwm

bspc config border_width        10

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config normal_border_color "#000000"

~/scripts/monitor

bspc rule -a Gimp follow=on floating=on
bspc rule -a heimdallr-client floating=on

cd ~/scripts/

./panel
