#! /bin/sh

bspc config border_width       2
bspc config window_gap         24
bspc config focused_border_color "#408cf3"

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config top_padding 32

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a feh fullscreen=true

~/.config/bspwm/panel &
