#! /bin/sh
#
# Example panel for LemonBoy's bar

WORKSPACE_ICON=$(echo -e "\uf0c8")
SELECTED_WORKSPACE_ICON=$(echo -e "\uf004")
PLAY_ICON=$(echo -e "\uf04b")
PAUSE_ICON=$(echo -e "\uf04c")
NEXT_ICON=$(echo -e "\uf04e")
PREV_ICON=$(echo -e "\uf04a")

WORKSPACE_FREE_COLOR="#ff02b5ff"
WORKSPACE_OCCUPIED_COLOR="#ff029cff"


num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		S*)
			# clock output
			clock=" ${line#?}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
						# active monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos"
						fi
						;;
					m*)
						# inactive monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos"
						fi
						;;
					O*)
						# focused occupied desktop
						wm_infos="$wm_infos %{F$WORKSPACE_OCCUPIED_COLOR}$SELECTED_WORKSPACE_ICON"
						;;
					F*)
						# focused free desktop
						wm_infos="$wm_infos %{F$WORKSPACE_FREE_COLOR}$SELECTED_WORKSPACE_ICON"
						;;
					U*)
						# focused urgent desktop
						wm_infos="$wm_infos %{F$WORKSPACE_OCCUPIED_COLOR}$SELECTED_WORKSPACE_ICON"
						;;
					o*)
						# occupied desktop
						wm_infos="$wm_infos %{F$WORKSPACE_OCCUPIED_COLOR}$WORKSPACE_ICON"
						;;
					f*)
						# free desktop
						wm_infos="$wm_infos %{F$WORKSPACE_FREE_COLOR}$WORKSPACE_ICON"
						;;
					u*)
						# urgent desktop
						wm_infos="$wm_infos %{F$WORKSPACE_OCCUPIED_COLOR}$WORKSPACE_ICON"
						;;
					L*)
						# layout
						;;
				esac
				shift
			done
			;;
		player)
			MUSIC_STATUS=$(mpc status | cut -d $'\n' -f 2 | awk '{print substr($1, 2, length($1)-2)}')
			if [ $MUSIC_STATUS = "playing" ]
			then
				MID_ICON="$PAUSE_ICON"
			else
				MID_ICON="$PLAY_ICON"
			fi

			MUSIC="$(mpc current) %{F$WORKSPACE_FREE_COLOR} %{A:mpc prev -q:}$PREV_ICON%{A} %{A:mpc toggle -q:}$MID_ICON%{A} %{A:mpc next -q:}$NEXT_ICON%{A}"
			;;
	esac

	BATTERY="$(battery)%"

	printf "%s\n" "%{l}${wm_infos}%{c}%{F-}${clock}%{r}$MUSIC    $BATTERY"
done
