#!/bin/bash

# This script gathers info and pipes it into a second script
# The second script processes information, formats it and sends it to the bar

# Pipe for all communication
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO" 
mkfifo "$PANEL_FIFO"

# Kill the bar if it's already running
BARPID="$(pidof bar)"
if (($? == 0)); then
	kill $BARPID
fi

clock -sf "C%A %B %d %H:%M" > "$PANEL_FIFO" &
while true; do echo "B$(acpi -b | awk -F, '{print $2}')" > "$PANEL_FIFO"; sleep 10; done &
while true; do ./volume_control; sleep 3; done &
while true; do echo "T$(acpi -t | awk '{print $4}')C" > "$PANEL_FIFO"; sleep 2; done &
while true; do echo "N$(nmcli con show --active | grep wlp3s0 | awk '{print $1}')" > "$PANEL_FIFO"; sleep 10; done &
while true; do ./music_control > "$PANEL_FIFO"; sleep 2; done &
bspc control --subscribe > "$PANEL_FIFO" &

MAIN_FONT="-lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1"
ICON_FONT="-misc-stlarch-medium-r-normal-*-10-100-75-75-c-80-iso10646-1"

cat "$PANEL_FIFO" | ./panel_bar | bar -f "$ICON_FONT,$MAIN_FONT" -g 1890x20+15+10 & 
wait
