#!/bin/bash

. config

while read line; do
	case $line in
		C*)
			CLOCK=${line#?}
			;;
		B*)
			BATTERY="%{F$FG_ICON_COLOR}$BATTERY_FULL_ICON%{F$FG_COLOR}${line#?}%"
			;;
		T*) 
			TEMP="%{F$FG_ICON_COLOR}$TEMP_ICON %{F$FG_COLOR}${line#?}"
			;;
		N*)
			WIFI="%{F$FG_ICON_COLOR}$WIFI_ICON %{F$FG_COLOR}"
			if [[ -z ${line#?} ]]
			then 
				WIFI="$WIFI Not connected.. "
			else 
				WIFI="$WIFI${line#?}"
			fi
			;;
		W*)
			WM_INFO=""
			data=$(echo $line | awk -F: '{ for(i=2;i<12;i++) printf "%s:",$i; }')
			IFS=':' read -a array <<< $data
			for i in {0..10}
			do
				case ${array[i]} in
					o*)
						WM_INFO+="%{F$FG_OCCUPIED_COLOR}%{B$BG_COLOR} $USED_DESKTOP_ICON "
						;;
					O*)
						WM_INFO+="%{F$FG_SELECTED_COLOR}%{B$BG_SELECTED_COLOR} $USED_DESKTOP_ICON "
						;;
					f*)
						WM_INFO+="%{F$FG_COLOR}%{B$BG_COLOR} $FREE_DESKTOP_ICON "
						;;
					F*) 
						WM_INFO+="%{F$FG_SELECTED_COLOR}%{B$BG_SELECTED_COLOR} $FREE_DESKTOP_ICON "
						;;
				esac
			done
			;;
		V*)
			VOLUME="%{F$FG_ICON_COLOR}$VOLUME_FULL_ICON%{F$FG_COLOR} ${line#?}%"
			;;
	esac

	printf "%s\n" "%{F$FG_COLOR}%{U$BG_COLOR}%{l+u-o} %{U$U_COLOR} $CLOCK%%{c+o}$WM_INFO%{F$FG_COLOR} %{r-o}$WIFI $TEMP $VOLUME $BATTERY "
done
