#!/bin/bash

. config

while read line; do
	case $line in
		C*)
			CLOCK=${line#?}
			;;
		X*)
			if [ ${#line} -ge 2 ]
			then
				TITLE="| ${line#?} |"
			else 
				TITLE=""
			fi
			;;
		B*)
			BATTERY="%{F$FG_ICON_COLOR}$BATTERY_FULL_ICON%{F$FG_COLOR}${line#?}%"
			;;
		T*) 
			TEMP="%{F$FG_ICON_COLOR}$TEMP_ICON %{F$FG_COLOR}${line#?}"
			;;
		Q*)
			MEM="%{F$FG_ICON_COLOR}$MEM_ICON %{F$FG_COLOR}${line#?}"
			;;
		E*)
			CPU="%{F$FG_ICON_COLOR}$CPU_ICON %{F$FG_COLOR}${line#?}%"
			;;

		N*)
			WIFI="%{F$FG_ICON_COLOR}$WIFI_ICON %{F$FG_COLOR}"
			if [[ -z ${line#?} ]]
			then 
				WIFI="$WIFI Not connected.. "
			else 
				WIFI="$WIFI${line#?}"
			fi
			;;
		M*)
			len=${#line}
			if [[ $len -eq 1 ]]
			then 
				MUSIC="%{F$FG_ICON_COLOR}$MUSIC_ICON%{F$FG_COLOR} Not playing.. "
			elif [[ "${line: -1}" == "+" ]]
			then
				(( len -= 2 ))
				MUSIC="%{F$FG_ICON_COLOR}$MUSIC_ICON$MUSIC_PLAY_ICON%{F$FG_COLOR} ${line:1:$len}"
			elif [[ "${line: -1}" == "-" ]]
			then
				(( len -= 2 ))
				MUSIC="%{F$FG_ICON_COLOR}$MUSIC_ICON$MUSIC_PAUSE_ICON%{F$FG_COLOR} ${line:1:$len}"
			fi
			;;
		W*)
			# this is getto
			WM_INFO=""
			max_count=$(($(bspc query -D | wc -l)+2))
			data=$(echo $line | awk -F: max=$max_count'{ for(i=1;i<max;i++) printf "%s:",$i; }')
			data=${data:1}

			IFS=':' read -a array <<< $data

			BG_SEL=$BG_SELECTED_COLOR

			for (( i=0; i<$max_count; i++ ))
			do
				name=${array[i]#?}
				case ${array[i]} in
					o*)
						FG=$FG_OCCUPIED_COLOR
						BG=$BG_COLOR
						;;
					O*)
						FG=$FG_SELECTED_COLOR
						BG=$BG_SEL
						;;
					f*)
						FG=$FG_COLOR
						BG=$BG_COLOR
						;;
					F*) 
						FG=$FG_SELECTED_COLOR
						BG=$BG_SEL
						;;
					u*)
						FG=$FG_OCCUPIED_COLOR
						BG=$BG_COLOR
						;;
					U*)
						FG=$FG_SELECTED_COLOR
						BG=$BG_SEL
						;;
					m*)
						FG=$FG_COLOR
						BG=$BG_COLOR
						BG_SEL=$BG_INACTIVE_COLOR
						name="$name:"
						;;
					M*)
						FG=$FG_COLOR
						BG=$BG_COLOR
						BG_SEL=$BG_SELECTED_COLOR
						name="$name:"
						;;
					L*)
						name=""
						;;
				esac
				WM_INFO+="%{F$FG}%{B$BG} $name "
				FG=$FG_COLOR
				BG=$BG_COLOR
			done
			;;
		V*)
			VOLUME="%{F$FG_ICON_COLOR}$VOLUME_FULL_ICON%{F$FG_COLOR} ${line#?}%"
			;;
	esac

	printf "%s\n" "%{l}$WM_INFO%{F- B-}$TITLE%{c}$CLOCK %{r}$MUSIC $MEM $CPU $WIFI $TEMP $VOLUME $BATTERY %{F- B-}"
done
