#!/bin/bash

BAT=$(acpi -b | awk -F, '{print $2}')
BAT=${BAT::-1}

STATUS=$(acpi -b | awk '{print $3}')
STATUS=${STATUS::-1}

if [ ! -f "/tmp/batstate" ]
then
	state=""
else 
	state=$(cat /tmp/batstate)
fi

echo $state

if [ $BAT -le 5 ] && [ $state != "critnotified" ] && [ $STATUS == "Discharging" ]
then
	notify-send -u critical Battery "Critical battery: $BAT%";
	state="critnotified"
elif [ $BAT -le 20 ] && [ $BAT -gt 5 ] && [ $state != "lownotified" ] && [ $STATUS == "Discharging" ]
then
	notify-send -u critical Battery "Low battery: $BAT%";
	state="lownotified"
elif [ $BAT -eq 100 ] && [ "$state" != "fullnotified" ]
then
	notify-send Battery "Fully charged: $BAT%";
	state="fullnotified"
fi

echo $state > "/tmp/batstate"
echo "B$BAT%"
