#!/bin/bash

if [[ $(xrandr | grep " connected" | wc -l) == 2 ]]
then
	xrandr --output VGA1 --auto --left-of eDP1
	bspc monitor ^1 -d 1 2 3 4 5 6 7 8 9 
	bspc monitor ^2 -d 1 2 3 4 5 6 7 8 9 

	bspc config -m ^1 window_gap 15
	bspc config -m ^2 window_gap 15
	bspc config -m ^2 top_padding 80
	bspc config -m ^1 top_padding 80
	bspc config -m ^2 bottom_padding 80
	bspc config -m ^1 bottom_padding 80
	bspc config -m ^2 right_padding 40
	bspc config -m ^1 right_padding 40
	bspc config -m ^2 left_padding 40
	bspc config -m ^1 left_padding 40

else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 

	bspc config -m ^1 window_gap 15
	bspc config top_padding 80
	bspc config bottom_padding 80
	bspc config left_padding 40
	bspc config right_padding 40
fi

eval $(cat ~/.fehbg)
