#!/bin/bash

STATUS=$(mpc status | wc -l)
SONG=$(mpc status | sed -n 1p)

if [ $STATUS -gt 1 ]
then
	tmp=$(mpc status | sed -n 2p | awk '{print $1}');
	if [ $tmp == "[playing]" ]
	then
		res="+"
	else
		res="-"
	fi
	echo "M$SONG$res";
else 
	echo "M"
fi
