#!/bin/bash

# temporary
. config

wminfofile="/tmp/wm"

# Data commands
datetime()
{
	local data=$(clock -f "%A %B %d %H:%M")
	echo "$data"
}

battery()
{
	echo "Battery: $(acpi -b | awk -F, '{print $2}')%" #$(battery)%
}

temp()
{
	echo "Temp: $(acpi -t | awk '{print $4}')C"
}

wifi()
{
	echo "Wifi: $(nmcli con show --active | grep wlp3s0 | awk '{print $1}')"
}

ram()
{
	echo "Ram: $(free -h | sed -n '2p' | awk '{print $3}')"
}

cpu()
{
	echo "CPU: $(mpstat 2 1 | awk '$13 ~ /[0-9.]+/ { print 100 - $13"%" }')"
}

#WM stuff
wminfo-start()
{
	bspc control --subscribe | wminfo-control
}

wminfo-control()
{
	while read line; do
		wminfo "$line"
	done
}

#TODO: Fix this up
wminfo()
{
	# this is getto
	WM_INFO=""
	max_count=$(($(bspc query -D | wc -l)+1+$(bspc query -M | wc -l)))
	local data=$(echo "$1" | awk -F: max=$max_count'{ for(i=1;i<max;i++) printf "%s:",$i; }')
	local data=${data:1}

	IFS=':' read -a array <<< $data

	BG_SEL=$BG_SELECTED_COLOR

	for (( i=0; i<$max_count; i++ ))
	do
		name=${array[i]#?}
		case ${array[i]} in
			o*)
				FG=$FG_OCCUPIED_COLOR
				BG=$BG_OCCUPIED_COLOR
				;;
			O*)
				FG=$FG_SELECTED_COLOR
				BG=$BG_SEL
				;;
			f*)
				FG=$FG_COLOR
				BG=$BG_COLOR
				;;
			F*) 
				FG=$FG_SELECTED_COLOR
				BG=$BG_SEL
				;;
			u*)
				FG=$FG_OCCUPIED_COLOR
				BG=$BG_OCCUPIED_COLOR
				;;
			U*)
				FG=$FG_SELECTED_COLOR
				BG=$BG_SEL
				;;
			m*)
				FG=$FG_COLOR
				BG=$BG_COLOR
				BG_SEL=$BG_INACTIVE_COLOR
				name="$name:"
				;;
			M*)
				FG=$FG_COLOR
				BG=$BG_COLOR
				BG_SEL=$BG_SELECTED_COLOR
				name="$name:"
				;;
			L*)
				name=""
				;;
		esac
		WM_INFO+="%{F$FG}%{B$BG} $name "
		FG=$FG_COLOR
		BG=$BG_COLOR
	done
	echo $WM_INFO > $wminfofile
	update
}

get-wminfo()
{
	cat "$wminfofile"
}

update()
{
	left_text="$(get-wminfo)"
	center_text="$(datetime)"
	right_text="$(ram) $(temp) $(wifi) $(battery)"

	buf="     $left_text %{F$FG_COLOR} %{c}"$center_text" %{F$FG_COLOR} %{r}"$right_text"     "
	echo "$buf"
}

wminfo-start &

while :; do
	update
	sleep 2
done
